- name: Kit Arduino
  image: https://github.com/Robotois/robotois-robert/blob/master/specs/images/renders/complete.png?raw=true
  description: Aprende electronica con el kit basico de Robotois, que consiste de un robot que puedes configurar para evadir obstáculos, seguir una linea y monitorear tu entorno con su sensores de humedad y temperatura.
  release_date: 2019-08-08
  videoId: GRT8VC34jiA
  items:
    - name: Placa UNO R3
      description: ELEGOO UNOR3 usa un ATMEGA16U2 como Chip de interfaz serie y un ATmega328P como microcontrolador haciéndolo más rápido en las transferencias y almacenamiento de datos y con más memoria.
      image: https://github.com/Robotois/robotois-robert/blob/master/specs/images/renders/Elego.png?raw=true
    - name: Chip L298N
      description: El módulo permite controlar el sentido y velocidad de giro de motores.
      image: https://github.com/Robotois/robotois-robert/blob/master/specs/images/renders/driver.png?raw=true
    - name: Micro motorreductor de metal
      description: Motores que brindan precisión de desplazamiento al robot.
      image: https://github.com/Robotois/robotois-robert/blob/master/specs/images/renders/motor.png?raw=true
