- name: Kit Arduino
  image: complete.png
  description: Aprende electronica con el kit basico de Robotois, que consiste de un robot que puedes configurar para evadir obstáculos, seguir una linea y monitorear tu entorno con su sensores de humedad y temperatura.
  release_date: 2019-08-08
  videoId: GRT8VC34jiA
  components:
    - name: Kit Arduino
      image: complete.png
      description: Aprende electronica con el kit basico de Robotois, que consiste de un robot que puedes configurar para evadir obstáculos, seguir una linea y monitorear tu entorno con su sensores de humedad y temperatura.
    - name: Placa UNO R3
      image: Elego.png
      description: ELEGOO UNOR3 usa un ATMEGA16U2 como Chip de interfaz serie y un ATmega328P como microcontrolador haciéndolo más rápido en las transferencias y almacenamiento de datos y con más memoria.
    - name: Chip L298N
      image: driver.png
      description: El módulo permite controlar el sentido y velocidad de giro de motores.
    - name: Micro motorreductor de metal
      image: motor.png
      description: Motores que brindan precisión de desplazamiento al robot.
